### ISSUE TITLE
トップページで ipa と apk のプロジェクトを視覚的に区別する

### ISSUE THREAD

**Issue by m0t0k1ch1** [kayac/alphawing#12]
りんごとドロイドくんを使うなど。

**Comment by m0t0k1ch1** [comment]
1プロジェクトで管理することになったので close

**Comment by nobii** [comment]
@m0t0k1ch1 逆に、appページでipaとapkのbundleを視覚的に区別する必要が出てきたので、別issue切りましょうかね。

**Comment by m0t0k1ch1** [comment]
@nobii 

#22 に含んでるつもりだったけど、別 issue 化したほうがやりやすいなら切っちゃってくださいまし！

**Comment by nobii** [comment]
@m0t0k1ch1 りょ。作業始めた時のステータスにもよりますが、 #22 に含まれてるということでOKす。
