### ISSUE TITLE
ipa対応 開発ブランチが欲しい

### ISSUE THREAD

**Issue by nobii** [kayac/alphawing#16]
ぜんぶmasterにやってると、細かく進めるのも大変なのでほしいです。

**Comment by m0t0k1ch1** [comment]
`topic/ipa` という branch を切りました。そこから `feature/ipa-***` みたいなブランチを切って `topic/ipa` に p-r する感じで進めましょう。

**Comment by m0t0k1ch1** [comment]
切ったので close

**Comment by nobii** [comment]
hai、ありがとー！！
