### ISSUE TITLE
ipa インストールのクッションページ

### ISSUE THREAD

**Issue by m0t0k1ch1** [kayac/alphawing#27]
ref. #10 

最低限、ボタンが1つあればよさそう

**Comment by nobii** [comment]
hai. クッションページの仮組みまでできたら教えて下さい。
layout & markupします。(って感じでよい?)

**Comment by m0t0k1ch1** [comment]
:ok_woman: 仮組みやります！

**Comment by m0t0k1ch1** [comment]
@nobii 

`topic/install_ipa` にテンプレート用意しました。`topic/install_ipa` から branch 切って作業するか直接コミットするかはお任せします。

**Comment by nobii** [comment]
@m0t0k1ch1 かくにんした、ありがとう！
押しても何も起きないリンクボタンを置いて、また返せば良いかしら?

**Comment by m0t0k1ch1** [comment]
yes!

**Comment by nobii** [comment]
@m0t0k1ch1 いったんできましたぜ。
(あとでもう少し、apple感を出したりするかも)
https://github.com/kayac/alphawing/commit/4472adff1458a8583d7a331b4b2f5e34ee917e03
