### ISSUE TITLE
bundle 一覧の既存レスポンス改修

### ISSUE THREAD

**Issue by m0t0k1ch1** [kayac/alphawing#37]
`apk` と `ipa` を出し分ける必要があるので。

**Comment by m0t0k1ch1** [comment]
@nobii 

ページ遷移なしで切り替えられるようにする？のであれば、それぞれの `bundle` のリストをレスポンスとして返せばいいかな？

**Comment by nobii** [comment]
そうっすね、一度にもらっちゃいたいです。
`.bundles.apk` `.bundles.ipa` とかがあればいいのかなー。

**Comment by m0t0k1ch1** [comment]
御意
