### ISSUE TITLE
初回認証後にTopページへ遷移してしまう問題

### ISSUE THREAD

**Issue by p-chin** [kayac/alphawing#5]
### 問題
`https://alphawing.hoge.com/bundle/1`の様なダウンロードページをalphawingを初めて利用するユーザーが開く場合に、初回認証後にTopページへ遷移してしまいます。

### 期待する挙動
認証後も最初にアクセスしたページに遷移して欲しいです。

**Comment by m0t0k1ch1** [comment]
@p-chin

#6 で対応しました
